Add notfound errors

diff --git a/vhd-format b/vhd-format
--- a/vhd-format
+++ b/vhd-format
@@ -6,6 +6,7 @@ if [ $EUID != 0 ]; then
     sudo "$0" "$@"
     exit $?
 fi
+[ -f "$1" ] || { echo "File not found: $1"; exit 1; }
 [ $# -lt 2 ] && FMT=ntfs || FMT=$2
 
 # find available loop device and bind it to the VHD
diff --git a/vhd-mount b/vhd-mount
--- a/vhd-mount
+++ b/vhd-mount
@@ -6,6 +6,8 @@ if [ $EUID != 0 ]; then
     sudo "$0" "$@"
     exit $?
 fi
+[ -f "$1" ] || { echo "File not found: $1"; exit 1; }
+[ -d "$2" ] || { echo "Folder not found: $2"; exit 1; }
 
 # consume args
 FILE=$1
diff --git a/vhd-umount b/vhd-umount
--- a/vhd-umount
+++ b/vhd-umount
@@ -6,6 +6,7 @@ if [ $EUID != 0 ]; then
     sudo "$0" "$@"
     exit $?
 fi
+[ -f "$1" ] || { echo "File not found: $1"; exit 1; }
 
 # unmount and detach loop-device
 LOOPDEV=$(losetup -j "$1" | awk -F: '{print $1}')
